In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [5]:
input_data = pd.read_csv("Churn_Modelling.csv")
input_data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
## Drop irrelevant columns
input_data = input_data.drop(['RowNumber','CustomerId','Surname'],axis=1)
input_data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
## Label encode gender
label_encode_gender = LabelEncoder()
input_data['Gender'] = label_encode_gender.fit_transform(input_data['Gender'])
input_data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [8]:
input_data[['Geography']] ## 2D array

     Geography
0       France
1        Spain
2       France
3       France
4        Spain
...        ...
9995    France
9996    France
9997    France
9998   Germany
9999    France

[10000 rows x 1 columns]

In [9]:
## one hot encode geography
onehot_encode_geo = OneHotEncoder()
onehot_encoded = onehot_encode_geo.fit_transform(input_data[['Geography']])
onehot_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
onehot_encode_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_df = pd.DataFrame(onehot_encoded.toarray(),columns=onehot_encode_geo.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [12]:
input_data = pd.concat([input_data.drop('Geography',axis=1),geo_df],axis=1)
input_data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [13]:
X = input_data.drop('EstimatedSalary',axis=1)
y = input_data['EstimatedSalary']

## split the dataset into training & testing

X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
## Save encoders and scalers as serialized pickle file in binary format
## wb = write binary mode
with open("reg_label_encoder_gender.pkl",'wb') as file:
    pickle.dump(label_encode_gender,file)

with open("reg_onehot_encoder_geo.pkl", 'wb') as file:
    pickle.dump(onehot_encode_geo,file)

with open("reg_scaler.pkl",'wb') as file:
    pickle.dump(scaler,file)

## ANN Regression problem statement

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1), # default activation function is linear
])
# for regression problem the activation function for output should be linear

WARNING:tensorflow:From d:\Study_Content\LLM\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [19]:
## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error', metrics=['mae'])
# loss function for regression will be mean_absolute_error
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
## Set up the TensorBoard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
log_dir = 'regression_logs/fit/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
## Set up the Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [22]:
## Train the model
history = model.fit(
    X_train, y_train, validation_data=(X_test,y_test), epochs=100,
    callbacks = [tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\Study_Content\LLM\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\Study_Content\LLM\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 7s 12ms/step - loss: 100375.2656 - mae: 100375.2656 - val_loss: 98508.5156 - val_mae: 98508.5156
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 99577.8047 - mae: 99577.8047 - val_loss: 96891.0859 - val_mae: 96891.0859
Epoch 3/100
250/250 [==============================] - 2s 9ms/step - loss: 96750.7266 - mae: 96750.7266 - val_loss: 92751.7734 - val_mae: 92751.7734
Epoch 4/100
250/250 [==============================] - 2s 10ms/step - loss: 91221.6250 - mae: 91221.6250 - val_loss: 85907.2344 - val_mae: 85907.2344
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 83242.0078 - mae: 83242.0078 - val_loss: 77153.7500 - val_mae: 77153.7500
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 73997.2031 - mae: 73997.2031 - val_loss: 68229.4141 - val_mae: 68229.4141
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 65171.5273 - mae: 65171.5273 - val_loss: 60564.1484 - val_mae: 60564.1484
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 58286.6914 - mae: 58286.6914 - val_loss: 55269.6797 - val_mae: 55269.6797
Epoch 9/100
250/250 [==============================] - 2s 8ms/step - loss: 53974.8789 - mae: 53974.8789 - val_loss: 52362.5664 - val_mae: 52362.5664
Epoch 10/100
250/250 [==============================] - 2s 6ms/step - loss: 51677.1523 - mae: 51677.1523 - val_loss: 51129.1133 - val_mae: 51129.1133
Epoch 11/100
250/250 [==============================] - 2s 8ms/step - loss: 50704.0391 - mae: 50704.0391 - val_loss: 50681.5312 - val_mae: 50681.5312
Epoch 12/100
250/250 [==============================] - 2s 8ms/step - loss: 50303.8164 - mae: 50303.8164 - val_loss: 50518.3203 - val_mae: 50518.3203
Epoch 13/100
250/250 [==============================] - 2s 9ms/step - loss: 50129.1094 - mae: 50129.1094 - val_loss: 50455.8906 - val_mae: 50455.8906
Epoch 14/100
250/250 [==============================] - 1s 6ms/step - loss: 50038.5352 - mae: 50038.5352 - val_loss: 50424.5234 - val_mae: 50424.5234
Epoch 15/100
250/250 [==============================] - 2s 7ms/step - loss: 49985.4492 - mae: 49985.4492 - val_loss: 50393.5352 - val_mae: 50393.5352
Epoch 16/100
250/250 [==============================] - 2s 9ms/step - loss: 49945.7344 - mae: 49945.7344 - val_loss: 50375.4766 - val_mae: 50375.4766
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 49912.5781 - mae: 49912.5781 - val_loss: 50355.6758 - val_mae: 50355.6758
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 49876.5352 - mae: 49876.5352 - val_loss: 50343.1250 - val_mae: 50343.1250
Epoch 19/100
250/250 [==============================] - 2s 6ms/step - loss: 49845.4297 - mae: 49845.4297 - val_loss: 50331.9883 - val_mae: 50331.9883
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 49820.0000 - mae: 49820.0000 - val_loss: 50316.5000 - val_mae: 50316.5000
Epoch 21/100
250/250 [==============================] - 1s 6ms/step - loss: 49794.7070 - mae: 49794.7070 - val_loss: 50310.5547 - val_mae: 50310.5547
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49777.6250 - mae: 49777.6250 - val_loss: 50288.5273 - val_mae: 50288.5273
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49755.6328 - mae: 49755.6328 - val_loss: 50289.2148 - val_mae: 50289.2148
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49736.6680 - mae: 49736.6680 - val_loss: 50284.3828 - val_mae: 50284.3828
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49720.0430 - mae: 49720.0430 - val_loss: 50271.9414 - val_mae: 50271.9414
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49706.0977 - mae: 49706.0977 - val_loss: 50265.6992 - val_mae: 50265.6992
Epoch 27/100
250/250 [==============================] - 2s 9ms/step - loss: 49685.5938 - mae: 49685.5938 - val_loss: 50263.6328 - val_mae: 50263.6328
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49676.2656 - mae: 49676.2656 - val_loss: 50271.1289 - val_mae: 50271.1289
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49660.9805 - mae: 49660.9805 - val_loss: 50268.8945 - val_mae: 50268.8945
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49650.1836 - mae: 49650.1836 - val_loss: 50273.9688 - val_mae: 50273.9688
Epoch 31/100
250/250 [==============================] - 1s 5ms/step - loss: 49636.3242 - mae: 49636.3242 - val_loss: 50269.9531 - val_mae: 50269.9531
Epoch 32/100
250/250 [==============================] - 2s 6ms/step - loss: 49625.9844 - mae: 49625.9844 - val_loss: 50275.4688 - val_mae: 50275.4688
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49617.2031 - mae: 49617.2031 - val_loss: 50267.0898 - val_mae: 50267.0898
Epoch 34/100
250/250 [==============================] - 3s 12ms/step - loss: 49604.0078 - mae: 49604.0078 - val_loss: 50263.8555 - val_mae: 50263.8555
Epoch 35/100
250/250 [==============================] - 1s 5ms/step - loss: 49592.4961 - mae: 49592.4961 - val_loss: 50269.7852 - val_mae: 50269.7852
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49586.3359 - mae: 49586.3359 - val_loss: 50267.7930 - val_mae: 50267.7930
Epoch 37/100
250/250 [==============================] - 1s 4ms/step - loss: 49577.3281 - mae: 49577.3281 - val_loss: 50261.9102 - val_mae: 50261.9102
Epoch 38/100
250/250 [==============================] - 1s 6ms/step - loss: 49567.5625 - mae: 49567.5625 - val_loss: 50270.3438 - val_mae: 50270.3438
Epoch 39/100
250/250 [==============================] - 1s 5ms/step - loss: 49561.1641 - mae: 49561.1641 - val_loss: 50264.2461 - val_mae: 50264.2461
Epoch 40/100
250/250 [==============================] - 2s 7ms/step - loss: 49550.8203 - mae: 49550.8203 - val_loss: 50256.8945 - val_mae: 50256.8945
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49539.3125 - mae: 49539.3125 - val_loss: 50256.9922 - val_mae: 50256.9922
Epoch 42/100
250/250 [==============================] - 2s 9ms/step - loss: 49532.6250 - mae: 49532.6250 - val_loss: 50259.2070 - val_mae: 50259.2070
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49524.6172 - mae: 49524.6172 - val_loss: 50258.3125 - val_mae: 50258.3125
Epoch 44/100
250/250 [==============================] - 1s 4ms/step - loss: 49517.0391 - mae: 49517.0391 - val_loss: 50262.3398 - val_mae: 50262.3398
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49509.6758 - mae: 49509.6758 - val_loss: 50261.7773 - val_mae: 50261.7773
Epoch 46/100
250/250 [==============================] - 1s 5ms/step - loss: 49502.4336 - mae: 49502.4336 - val_loss: 50271.0938 - val_mae: 50271.0938
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49497.3164 - mae: 49497.3164 - val_loss: 50267.7930 - val_mae: 50267.7930
Epoch 48/100
250/250 [==============================] - 2s 7ms/step - loss: 49489.8242 - mae: 49489.8242 - val_loss: 50268.4336 - val_mae: 50268.4336
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49480.8672 - mae: 49480.8672 - val_loss: 50265.8945 - val_mae: 50265.8945
Epoch 50/100
250/250 [==============================] - 1s 5ms/step - loss: 49477.7461 - mae: 49477.7461 - val_loss: 50266.1523 - val_mae: 50266.1523

In [23]:
## Load tensorboard extension
%load_ext tensorboard

In [25]:
%tensorboard --logdir regression_logs/fit

Reusing TensorBoard on port 6006 (pid 10968), started 0:01:19 ago. (Use '!kill 10968' to kill it.)

In [26]:
## Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Test loss = {test_loss}")
print(f"Test MAE = {test_mae}")

63/63 [==============================] - 0s 2ms/step - loss: 50256.8945 - mae: 50256.8945
Test loss = 50256.89453125
Test MAE = 50256.89453125

In [27]:
model.save('regression_model.h5')

d:\Study_Content\LLM\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(